---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include kelleyblackmore.nginx.install role
      include_role:
        name: kelleyblackmore.nginx.install
      vars:
        nginx_version: "stable"
        nginx_http_port: 80
        
    - name: Verify Nginx is running
      uri:
        url: http://localhost:80
        status_code: 200
      register: result
      until: result.status == 200
      retries: 5
      delay: 1
      
    - name: Include kelleyblackmore.nginx.upgrade role
      include_role:
        name: kelleyblackmore.nginx.upgrade
      vars:
        nginx_upgrade_version: "latest"
        nginx_upgrade_backup: true
