---
# Version can be "latest", "stable", or a specific version number
nginx_version: "latest"

# Whether to enable Nginx service on boot
nginx_service_enabled: true
nginx_service_state: "started"

# User and group to run Nginx as
nginx_user: "nginx"
nginx_group: "nginx"

# Basic configuration
nginx_worker_processes: "auto"
nginx_worker_connections: 1024
nginx_keepalive_timeout: 65

# SSL configuration (if enabled)
nginx_ssl_enabled: false
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"

# HTTP configuration
nginx_http_enabled: true
nginx_http_port: 80

# Custom error pages
nginx_custom_error_pages: false

# Package management settings
nginx_package_state: present

# Configuration paths
nginx_conf_path: "/etc/nginx/nginx.conf"
nginx_conf_dir: "/etc/nginx/conf.d"
nginx_default_site_path: "/etc/nginx/conf.d/default.conf"

# Create virtual hosts directories
nginx_create_vhost_dirs: true
nginx_vhost_dir: "/etc/nginx/sites-available"
nginx_vhost_enabled_dir: "/etc/nginx/sites-enabled"

# Log settings
nginx_log_dir: "/var/log/nginx"
nginx_access_log: "{{ nginx_log_dir }}/access.log"
nginx_error_log: "{{ nginx_log_dir }}/error.log"
nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

# Repo settings for different distributions
nginx_yum_repo_url: "https://nginx.org/packages/{% if nginx_version == 'mainline' %}mainline/{% endif %}{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/$basearch/"
nginx_apt_repo_url: "https://nginx.org/packages/{% if nginx_version == 'mainline' %}mainline/{% endif %}{{ ansible_distribution|lower }}/"
